# Generated by Django 5.1.3 on 2024-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_items',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
