# Generated by Django 5.1.3 on 2024-11-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_add_items_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_items',
            new_name='add_item',
        ),
    ]
