# Generated by Django 5.1.3 on 2024-12-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_additem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='notification_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='additem',
            name='notification_time',
            field=models.TimeField(default=None),
        ),
    ]
