# Generated by Django 5.1.3 on 2024-12-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_alter_additem_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='notification_date',
        ),
        migrations.RemoveField(
            model_name='additem',
            name='notification_time',
        ),
    ]
