# Generated by Django 5.1.3 on 2024-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_remove_additem_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
